### ISSUE TITLE
opkg should support https

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/firmware#148]
At the moment opkg does not support https urls because we build wget without openssl.

**Comment by lgierth** [comment]
I started looking into using OPKG's curl backend with polarssl. It builds, just needs testing, obviously -- then I'll also have numbers regarding disk space needs.

http://paste.debian.net/142421/

I also asked jow for feedback on the approach.

**Comment by booo** [comment]
@lgierth Very nice. Can you create a patch for the current firmware?

**Comment by lgierth** [comment]
In the end, I went with a different approach as suggested by Felix Fietkau:

https://github.com/freifunk-berlin/firmware/compare/opkg-https

> Changes opkg's download backend from wget to uclient, which is
easier to integrate with SSL libraries, thanks to libustream.
>
> Both libustream and libpolarssl are already present, so the other
half of the job is already done -- yay!

This also means that the additional disk space required should be 0.

This patch isn't quite enough yet to make https://buildbot.berlin.freifunk.net/buildbot/ work, because of the self-signed SSL certificate. We'd either need to make opkg pass `--no-certificate-check` to uclient-fetch, or add the certificate to the firmware image -- I'd prefer the latter.

**Comment by lgierth** [comment]
Here's how this currently looks:

```
root@12d24202f654:/tmp# opkg install https://buildbot.berlin.freifunk.net/buildbot/unstable/x86/302/packages/packages/horst_4.2-1_x86.ipk
Downloading https://buildbot.berlin.freifunk.net/buildbot/unstable/x86/302/packages/packages/horst_4.2-1_x86.ipk.
Collected errors:
 * opkg_download: Failed to download https://buildbot.berlin.freifunk.net/buildbot/unstable/x86/302/packages/packages/horst_4.2-1_x86.ipk, uclient-fetch returned 5.

root@12d24202f654:/tmp# uclient-fetch https://buildbot.berlin.freifunk.net/buildbot/unstable/x86/302/packages/packages/horst_4.2-1_x86.ipk
Downloading 'https://buildbot.berlin.freifunk.net/buildbot/unstable/x86/302/packages/packages/horst_4.2-1_x86.ipk'
Connecting to Unknown:0
Connection error: Invalid SSL certificate

root@12d24202f654:/tmp# uclient-fetch --no-check-certificate https://buildbot.berlin.freifunk.net/buildbot/unstable/x86/302/packages/packages/horst_4.2-1_x86.ipk
Downloading 'https://buildbot.berlin.freifunk.net/buildbot/unstable/x86/302/packages/packages/horst_4.2-1_x86.ipk'
Connecting to Unknown:0
Writing to 'horst_4.2-1_x86.ipk'
Download completed (33378 bytes)
```

**Comment by booo** [comment]
The certificate is not self signed! We have to install certificates. Maybe it's enough to install our certificate chain and the openwrt certificate chain?

General information about certificates and openwrt: http://wiki.openwrt.org/doc/howto/wget-ssl-certs#adding_certificates_through_opkg

Can we remove wget from the build-in package list after this change?

**Comment by andrenarchy** [comment]
+1 for just shipping our certificate chain (startcom+starfield) for firmware size reasons.

wget is compiled into busybox, I don't know if removing it will result in a significantly smaller binary.

**Comment by lgierth** [comment]
> The certificate is not self signed! We have to install certificates

Oh word, I forgot that OpenWrt doesn't install a cert chain unless asked to. I'll try the instructions you linked.

> wget is compiled into busybox, I don't know if removing it will result in a significantly smaller binary.

And opkg didn't even specify a dependency on it. Is there anything else that potentially depends on wget? OWM and the like?

On a slightly different note, could I get the buildbot's nginx.conf? I wanna use this patch with https://buildbot.meshwith.me/snapshots for the Meshbox firmware too, but it looks like its certificate is too cutting-edge or so. Getting more validation info out of uclient-fetch is non-trivial, and I'd like to see what I can change in order to make it work there.

**Comment by lgierth** [comment]
Okay, this should do the trick. uclient-fetch doesn't support a directory of certificates, as e.g. OpenSSL does -- thus I hardcoded startssl.pem for now. Unfortunately there's no other way to pass the certificate file to uclient-fetch, at the moment. nbd or jow or someone else will hopefully take care of that.

I added a package which installs startssl.pem, and also declares a dependency on libustream-polarssl. Inclusion of this package will thus be sufficient to enable HTTPS support for opkg.

Changeset #1: https://github.com/freifunk-berlin/firmware/compare/opkg-https
Changeset #2: https://github.com/freifunk-berlin/firmware-packages/compare/ssl-files

One thing that's left to do is updating /etc/opkg.conf -- I haven't looked at that yet.

**Comment by lgierth** [comment]
The certificate I picked is https://www.startssl.com/certs/ca.pem

**Comment by lynxis** [comment]
@lgierth what about using /etc/ssl/cert.pem. It's the same way as wget in BB behaves.

**Comment by lgierth** [comment]
That's a good idea, will have it ready for the next meetup.

@jow- what do you think? It might be an alternative to loading certificates from a directory. (re: our chat on Jan 28th)

**Comment by jow-** [comment]
Whatever you prefer, I don't have time to work on that atm.

**Comment by booo** [comment]
@lgierth The changes I talked about the yesterday: http://git.openwrt.org/?p=openwrt.git;a=log;h=1684cba46b0193b763091f1c439d256578cf3c85

**Comment by SvenRoederer** [comment]
* buildbots certs are now signed by LetsEncrypt
* with https://github.com/freifunk-berlin/firmware/commit/d888c21df67c5f2e424fa2955849890ac4a66be8 we changed to LEDE, which gave support of https.
