### ISSUE TITLE
LuCI profile_berlin updates

### ISSUE THREAD

**Issue by sarumpaet** [freifunk-berlin/firmware#245]
https://github.com/freifunk-berlin/luci/tree/freifunk_berlin_updates collects profile_berlin updates to be pushed upstream. Not sure about some things. We should probably keep olsrd defaults in upstream? And introduce olsrd6 defaults?
@cholin @booo @andrenarchy

**Comment by sarumpaet** [comment]
Updated the commit to keep OLSR and OWM settings.

**Comment by booo** [comment]
@sarumpaet Why did you keep the owm settings? I removed them once because the defaults where sane for our setup.

We can keep the olsrd defaults in upstream and we should maybe introduce olsrd6 defaults. The problem here is that we don't use these defaults anyway. In the worst case they create broken configurations with other assistants. Maybe we should add a comment?

**Comment by sarumpaet** [comment]
@booo OWM: Ok, it wasn't clear that the OWM package defaults to api.openwifimap.net already; as with the other settings I thought the OWM parts got removed since they were replaced by uci-defaults. Still, an indication that we use OWM (and not some other map) would be nice...

**Comment by booo** [comment]
Why do we need the indication that we use the OWM? I don't think there is software e.g. meshkit that makes any use of this information. If we just need a bit of documentation for the user we should add this to the README.

**Comment by sarumpaet** [comment]
Further discussion see #310
