### ISSUE TITLE
luci - no redirect to https

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/firmware#366]
on full-platforms the https-server is enabled, but clients do not get forwarded automatically to https when accessing http-version.
This was done in former builds.

**Comment by sarumpaet** [comment]
This is intentional (set somewhere in defaults/migration) since we don't have a valid HTTPS certificate for frei.funk, causing an error in the browser which will puzzle users. Also, there might be browsers which don't even allow overriding in that case, see various mobile browsers.

If you know what you do you can still use HTTPS manually (as with Kathleen <=0.1.2).
