### ISSUE TITLE
remove freifunk-watchdog

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/firmware#52]
The functionality of the freifunk-watchdog package overlaps at some points with functionality provided by procd. Maybe we should remove the package or update the source code.

http://luci.subsignal.org/trac/browser/luci/trunk/contrib/package/freifunk-watchdog

**Comment by booo** [comment]
There is no procd support yet :/ We can have a look at this. Shouldn't be to complex. Working draft is here:

https://github.com/booo/openwrt-routing/tree/olsrd_procd

Should we wait with the removal till we implemented support for procd in the olsr package?

**Comment by lgierth** [comment]
Updated olsrd+procd tree here (WIP): https://github.com/lgierth/openwrt-routing-packages/compare/olsrd_procd

**Comment by cholin** [comment]
To get rid of `freifunk-watchdog` we have to break up this whole legacy dependency chain in luci. `freifunk-watchdog` gets selected by `luci-mod-freifunk-community`. This package itself is a meta-package (no content) and selects the following packages:

```
+iptables-mod-nat-extra +iptables-mod-ipopt +luci-app-splash \
+olsrd +olsrd-mod-dyn-gw-plain +olsrd-mod-jsoninfo +olsrd-mod-nameservice \
+olsrd-mod-watchdog +kmod-tun +ip +freifunk-watchdog +luci-app-olsr \
+luci-app-olsr-services +freifunk-gwcheck +freifunk-mapupdate
```

We do not use packages like:

* `freifunk-gwcheck`
* `freifunk-mapupdate`
* `luci-app-splash`
* `olsrd-mod-watchdog`

In general this meta package does not make much sense to us anymore because we have our packages lists in `packages/` for that. I would favor to get rid of it instead of patching the meta-package and explicitly mention these packages in `packages/*.txt`. This would mean as well that we don't use `luci-mod-freifunk` as well. The benefits of this would to reduce complexity of dependency chains, get rid of legacy code and save space (a side note: Gluon did the same).

**Comment by andrenarchy** [comment]
+1 for explicit package list!

**Comment by lynxis** [comment]
+1

**Comment by sarumpaet** [comment]
I'm working on the 4mb_flash branches currently. I don't see luci-mod-freifunk-community getting included anywhere (grep for example http://buildbot.berlin.freifunk.net/builders/ar71xx/builds/552/steps/shell_1/logs/stdio - that's for master), but luci-mod-freifunk *does* get included (by ffwizard and luci-app-owm). ffwizard doesn't really depend on luci-mod-freifunk apart from hooking into its menu structure; for the 4MB version I'm patching the wizard not to depend on luci-mod-freifunk. As a side note, eventually we should probably move to some luci-mod-freifunk-berlin package instead of ffwizard+mod-freifunk.

Concerning freifunk-watchdog - that should be gone from the images just by deleting it from packages/default.txt.

**Comment by booo** [comment]
Maybe we should remove this one too: https://github.com/openwrt/luci/blob/master/contrib/package/freifunk-common/files/usr/sbin/ff_olsr_watchdog

**Comment by sarumpaet** [comment]
fixed by https://github.com/freifunk-berlin/firmware-packages/commit/59791e2594215bfdb3306daa9dbe3685059bd30a etc
