### ISSUE TITLE
softbrick of cpe210 v2

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/firmware#571]
according to https://lists.berlin.freifunk.net/pipermail/berlin/2018-May/037867.html the current code for support of the TPlink CPe210v2 (https://github.com/freifunk-berlin/firmware/commit/1e1ba9580691fb92178cf6f5fd6beb8869c3192f) leads to soft-bricks.

possibly https://github.com/openwrt/openwrt/pull/937 is a patch with recent working code.

**Comment by bobster-galore** [comment]
Do we have to wait for the upstream fix or can we cherry pick?
Has anyone tested if it is working with that pr?

**Comment by SvenRoederer** [comment]
It reads as the patch will work.
This patch just needs to replace the current "buggy"

**Comment by adrianschmutzler** [comment]
Maybe it's the same problem I had with the initial PR for the CPE210: The config for the CPE210v2 inherits the config from the v1. At some point, the configuration for the v1 was altered to increase the kernel partition size. However, there is a second location where the partition sizes are stored and this one may have the old sizes depending on when you implemented it:

https://github.com/openwrt/openwrt/pull/642#issuecomment-386123966

This should be fixed in the new PR.

However, I'm not sure whether this change will have an impact on the current state of the PR:

https://github.com/openwrt/openwrt/commit/805e59cdcc2b6b2bb3f7583d8ccdb932e6cdeb7b

**Comment by bobster-galore** [comment]
Will this be fixed if we rely on the latest openwrt? https://github.com/freifunk-berlin/firmware/issues/583

**Comment by SvenRoederer** [comment]
this board should be fixed in OpenWrt-master and OpenWrt-18.06

**Comment by booo** [comment]
Please reopen if you encounter problems with this agian.
